notifications:
  email:
    recipients:
      - cfsdocs@us.ibm.com
    on_failure: always # default: always
    on_success: never # default: change

provider: script

matrix:
  include:
   - language: python
     python: 3.7
     env:
       - name="Markdown Enricher for Continuous Integration and Continuous Deployment"
     script:
       - export branch=internal-beta-dev
       - bash <(curl -O -u ${GH_TOKEN}:x-oauth-basic -sL https://github.ibm.com/cloud-docs-automation/md-enricher-for-cicd/archive/$branch.zip)
       - |
          if unzip -q -o $branch.zip; then
            echo "Cloned repo unzipped."
          else
            echo $? 
            printf "ERROR: The md-enricher-for-cicd repo could not be cloned. The GH_TOKEN might be expired."
            travis_terminate 1
          fi
       - cd ${TRAVIS_BUILD_DIR}/*md-enricher-for-cicd-*/md-enricher-for-cicd
       - python ${TRAVIS_BUILD_DIR}/*md-enricher-for-cicd-*/md-enricher-for-cicd/repos/locations-ibm-cloud-create.py
       - python ${TRAVIS_BUILD_DIR}/*md-enricher-for-cicd-*/md-enricher-for-cicd/start.py --LOCATIONS_FILE ${TRAVIS_BUILD_DIR}/*md-enricher-for-cicd-*/md-enricher-for-cicd/locations.json --CONFIG_FILE ${TRAVIS_BUILD_DIR}/*md-enricher-for-cicd-*/config/config-source.ini --SLACK_WEBHOOK ${SLACK_WEBHOOK} --IBM_CLOUD_DOCS_PRODUCT_NAME_CHECK --IBM_CLOUD_DOCS | tee -a ${TRAVIS_BUILD_DIR}/.md-enricher-for-cicd.log ; travis_terminate ${PIPESTATUS[0]}
